export const EXERCISE_DATABASE = {
  Pecho: [
    { id: 'p1', name: 'Press de Banca Plano (Barra)', gif: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'p2', name: 'Press Inclinado (Mancuernas)', gif: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'p3', name: 'Aperturas en Peck Deck', gif: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'p4', name: 'Fondos en Paralelas (Dips)', gif: 'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHJueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZzRueXF4ZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'p5', name: 'Cruce de Poleas Altas', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
  ],
  Espalda: [
    { id: 'e1', name: 'Dominadas (Pull-ups)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'e2', name: 'Remo con Barra', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'e3', name: 'Jalón al Pecho', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'e4', name: 'Remo en Polea Baja', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'e5', name: 'Pull-over con Polea Alta', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'e6', name: 'Hiperextensiones', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
  ],
  Piernas: [
    { id: 'l1', name: 'Sentadilla Libre', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l2', name: 'Prensa de Piernas 45°', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l3', name: 'Peso Muerto Rumano', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l4', name: 'Extensión de Cuádriceps', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l5', name: 'Curl Femoral Tumbado', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l6', name: 'Zancadas (Lunges)', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
    { id: 'l7', name: 'Elevación de Talones (Gemelos)', gif: 'https://media.giphy.com/media/l0HlSrn79Gk4WzR6w/giphy.gif' },
  ],
  Hombros: [
    { id: 'h1', name: 'Press Militar (Barra)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'h2', name: 'Elevaciones Laterales', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'h3', name: 'Pájaros (Deltoide Posterior)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'h4', name: 'Press Arnold', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'h5', name: 'Facepulls', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
  ],
  Brazos: [
    { id: 'b1', name: 'Curl con Barra (Bíceps)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'b2', name: 'Martillo (Mancuerna)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'b3', name: 'Extensión en Polea (Tríceps)', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'b4', name: 'Press Francés', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'b5', name: 'Curl Predicador', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
    { id: 'b6', name: 'Dippings entre bancos', gif: 'https://media.giphy.com/media/3o7TKMGpxx6xYF9lRe/giphy.gif' },
  ],
};